export const RoutineTypes = {
  ROUTINE_FETCH_START: 'ROUTINE_FETCH_START',
  ROUTINE_FETCH_SUCCESS: 'ROUTINE_FETCH_SUCCESS',
  ROUTINE_FETCH_ERROR: 'ROUTINE_FETCH_ERROR',
  ROUTINE_DELETE_START: 'ROUTINE_DELETE_START',
  ROUTINE_DELETE_SUCCESS: 'ROUTINE_DELETE_SUCCESS',
  ROUTINE_DELETE_ERROR: 'ROUTINE_DELETE_ERROR',
  ROUTINE_CREATE_START: 'ROUTINE_CREATE_START',
  ROUTINE_CREATE_SUCCESS: 'ROUTINE_CREATE_SUCCESS',
  ROUTINE_CREATE_ERROR: 'ROUTINE_CREATE_ERROR',
  CLEANUP: 'CLEANUP',
};
